site_name: "Terraform Provider: Confluence"
site_url: https://github.com/elc-online/terraform-provider-confluence
repo_url: https://github.com/elc-online/terraform-provider-confluence
nav:
- Getting Started: index.md
- Resources:
  - confluence_attachment: resources/confluence_attachment.md
  - confluence_content: resources/confluence_content.md
  - confluence_space: resources/confluence_space.md
theme: readthedocs
